version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.0
  serverless: circleci/serverless-framework@1.0.1
  node: circleci/node@3.0.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    executor: serverless/default
    steps:
      - checkout
      - node/install:
          install-npm: true
          node-version: latest
      - run: node --version
      - run: npm install
      - aws-cli/setup
      - serverless/setup
      - run: serverless deploy -s prod -v
